name: js_interop
description: Common utilities to use JavaScript interoperability with Dart
version: 0.0.1
homepage: https://github.com/jodinathan/js_interop_dart

environment:
  sdk: '>=2.15.0-edge <3.0.0'

dependencies:
  js: ^0.6.3

dev_dependencies:
  lints: ^1.0.1
